package org.example.tools;

public enum ToolName {
    MONOCHROME_CONVERTER,
    INVERSOR,
    GAUSS_FILTER,
    SHARPENER,
    EMBOSSER,
    GAMMA_CORRECTOR,
    ROBERTS_OPERATOR,
    SOBEL_OPERATOR,
    FLOYD_STEINBERG_DITHER,
    ORDERED_DITHER,
    WATERCOLORIZER,
    IMAGE_ROTATOR;
}
