package org.example.parameters;

public enum ParameterName {
    GAUSS_FILTER_WINDOW_SIZE,
    GAMMA,
    BINARIZATION,
    IMAGE_ANGLE,
    QUANTIZATION_NUMBER_RED,
    QUANTIZATION_NUMBER_GREEN,
    QUANTIZATION_NUMBER_BLUE;
}